### ISSUE TITLE
"requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased/tree/main?recursive=True&expand=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f07ec283c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))")".

### ISSUE THREAD

**Issue by HYTHYThythyt** [CVI-SZU/QA-CLIMS#2]
Hello, author.
I have some problems where I using BLIP to generate the answers of the predefined questions.
The problem arose when I running this script: get_blip_vqa_results.py, more specific error is being in this method: tokenizer = BertTokenizer.from_pretrained('bert-base-uncased').
Eorro description is "requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased/tree/main?recursive=True&expand=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f07ec283c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))")".
Thank you for your answers.

**Comment by Tiiiktak** [comment]
Hi, sorry for the late reply.
When using the BLIP model for the first time, it will automatically access Hugging Face to update model weights. Checking and configuring your network environment may resolve this issue.
