### ISSUE TITLE
For COCO Dataset

### ISSUE THREAD

**Issue by HYTHYThythyt** [CVI-SZU/QA-CLIMS#3]
Hi, when the codes for training coco and V1-WR codes can be uploaded?

**Comment by HYTHYThythyt** [comment]
thank you!

**Comment by Tiiiktak** [comment]
Hi, sorry for the late reply.

We have released the training code for the COCO dataset, please follow the instructions in README.

Thank you for your interest in our work.  Btw, welcome to star our QA-CLIMS😊

**Comment by HYTHYThythyt** [comment]
Thank you for your great job! I have star it.
