### ISSUE TITLE
DeepLabV1-WR38

### ISSUE THREAD

**Issue by HYTHYThythyt** [CVI-SZU/QA-CLIMS#4]
Hi, author, I have reproduce the DeepLabV1-WR38 according to the reference you had pointed in the CLIMS issues(Hi, you can refer to this [repo](https://github.com/YudeWang/semantic-segmentation-codebase/tree/main/experiment/seamv1-pseudovoc). Btw, welcome to star CLIMS:)), but the result have a huge gap with your paper. What is the problem on it? Any help is appreciate. Thank you for your great job.

**Comment by Tiiiktak** [comment]
Hi, you can try the following config in the `config.py`:

```python
config_dict = {
		'EXP_NAME': 'qa_clims',
		'GPUS': 1,

		'DATA_NAME': 'VOCDataset',
		'DATA_YEAR': 2012,
		'DATA_AUG': True,
		'DATA_WORKERS': 4,
		'DATA_MEAN': [0.485, 0.456, 0.406],
		'DATA_STD': [0.229, 0.224, 0.225],
		'DATA_RANDOMCROP': 512,
		'DATA_RANDOMSCALE': [0.5, 2.0],
		'DATA_RANDOM_H': 15,
		'DATA_RANDOM_S': 15,
		'DATA_RANDOM_V': 15,
		'DATA_RANDOMFLIP': 0.5,
		'DATA_PSEUDO_GT': '/path/to/sem_seg',
		
		'MODEL_NAME': 'deeplabv1',
		'MODEL_BACKBONE': 'resnet38',
		'MODEL_BACKBONE_PRETRAIN': True,
		'MODEL_BACKBONE_DILATED': None,
		'MODEL_BACKBONE_MULTIGRID': None,
		'MODEL_BACKBONE_DEEPBASE': None,
		'MODEL_NUM_CLASSES': 21,
		'MODEL_FREEZEBN': False,
		'MODEL_SCALES': [0.5, 0.75],

		'TRAIN_LR': 0.0008,
		'TRAIN_MOMENTUM': 0.9,
		'TRAIN_WEIGHT_DECAY': 0.0005,
		'TRAIN_BN_MOM': 0.0003,
		'TRAIN_POWER': 0.9,
		'TRAIN_BATCHES': 6,	
		'TRAIN_SHUFFLE': True,
		'TRAIN_MINEPOCH': 0,
		'TRAIN_ITERATION': 30000,
		'TRAIN_TBLOG': True,

		'TEST_PERIOD': 'test', # val / test
		'TEST_MODE': 'crf', # mode for test, infer/crf
		'TEST_MULTISCALE': [0.5, 1.0, 1.5, 2.0],
		'TEST_REDUCTION': 'mean',
		'TEST_FLIP': True,
		'NUM_WORKERS': 128,
		'CRF': {
			'ITER_MAX': 10,
			'POS_W': 3,
			'POS_XY_STD': 1,
			'BI_W': 4,
			'BI_XY_STD': 67,
			'BI_RGB_STD': 3
		},
		'TEST_BATCHES': 1,
}
```

**Comment by HYTHYThythyt** [comment]
I have some questions about the config file, what are those params "MODEL_SCALES", "MODEL_BACKBONE_DILATED", "MODEL_BACKBONE_MULTIGRID", "MODEL_BACKBONE_DEEPBASE"? They are not present in the [semantic-segmentation-codebase](https://github.com/YudeWang/semantic-segmentation-codebase). 
And the params for test and val in the config, the semantic-segmentation-codebase had not presented some of those. Any help is appreciated, thank you!

**Comment by HYTHYThythyt** [comment]
The main puzzling param is "TEST_REDUCTION", where use it in the [semantic-segmentation-codebase](https://github.com/YudeWang/semantic-segmentation-codebase). I have not found it in the codes, thank you!

**Comment by Tiiiktak** [comment]
Hi, sorry for the confusion.

The params `MODEL_BACKBONE_DILATED`, `MODEL_BACKBONE_MULTIGRID`, `MODEL_BACKBONE_DEEPBASE` is used by the `generate_net()` at [train.py#L52](https://github.com/YudeWang/semantic-segmentation-codebase/blob/a40f6c6b08710ee1799832c97331cf967e1c5cdb/experiment/deeplabv3%2Bvoc/train.py#L52C139-L52C148). However, these params were not used by the `deeplabv1.py`, so ignore them.

For the param `MODEL_SCALES`, we apply multi-scale training from [kazuto1011/deeplab-pytorch](https://github.com/kazuto1011/deeplab-pytorch).

For the `TEST_*` params, we also apply the CRF options from [kazuto1011/deeplab-pytorch](https://github.com/kazuto1011/deeplab-pytorch/blob/master/libs/utils/crf.py), and some multi-processing code to speed up the process.

You can find our modified  code for training the DeepLabV1-WR38 model at [this link](https://drive.google.com/file/d/1OaBxDTRTQLCJjgBS2lkeWOxfdo4MQbqU/view?usp=drive_link)

**Comment by HYTHYThythyt** [comment]
Thank you for your careful replies! The (DeepLabV1-WR38 model at [this link](https://drive.google.com/file/d/1OaBxDTRTQLCJjgBS2lkeWOxfdo4MQbqU/view?usp=drive_link))'s permissions have been set, could you authorize me to access it? thank you!

**Comment by Tiiiktak** [comment]
done

**Comment by HYTHYThythyt** [comment]
Thank you for your codes. I also have some questions about the deeplabv2 from your another great job [CLIMS](https://github.com/CVI-SZU/CLIMS), I also can not reach the result in the QA-CLIMS paper by just using the V2 from the CLIMS, are there any change in the deeplabv2 for QA-CLIMS? Any help is appreciate, Thank you!

**Comment by Tiiiktak** [comment]
Hi, we use the same configuration as CLIMS in [this file](https://github.com/CVI-SZU/CLIMS/blob/master/segmentation/deeplabv2/configs/voc12_imagenet_pretrained.yaml) to train the deeplabv2, but change batch_size to 5. 

Please check if the generated pseudo labels get the similar results as ours, which can be evaluated by `step/eval_sem_seg.py`.

Otherwise, make sure you have apply the CRF options on the generated predictions, just like https://github.com/CVI-SZU/CLIMS/blob/f9546d32ad9b4545577eebdc9e4d879aff3366d7/segmentation/deeplabv2/run_voc12_imagenet_pretrained.sh#L4

**Comment by HYTHYThythyt** [comment]
According to your description, the main difference is the BS. I also use the crf for post-process, but the segmentation result is poorer than yours about 0.4~. 
And, I use your coco-codes for training coco-step, I got the problem in this [train_qa_clims.py#194](https://github.com/CVI-SZU/QA-CLIMS/blob/master/step_coco/train_qa_clims.py#L194), the exception is "IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number", did you had encountered this exception before? 
I also want to know your server config for coco, I use 2GPU that 48G per-GPU, I got the CUDA out of memory problem. 
Any help is very appreciate, thank you!

**Comment by Tiiiktak** [comment]
Hi, I have pushed a new version of `step_coco/train_qa_clims.py`, it may fix the IndexError you mentioned. 

We use 4 x 32G memory GPUs to train the coco model.

**Comment by HYTHYThythyt** [comment]
Thank, I also wnat to know your coco miou in evaluation step for 10000 images. And the V2's config for the coco step. Thank you again for your great job.

**Comment by HYTHYThythyt** [comment]
And how long have you spend for training coco dataset with deeplabv2? thank!

**Comment by Tiiiktak** [comment]
We got ～0.424 in evaluating 10000 images, and the final miou is ～0.421.
We train deeplabv2 with batch size 10 for 100000 steps, other configurations are the same as voc.
I don't really remember the exact amount of time spent on training, it might take you more than 20 hours to train deeplabV2, and when you do the crf operation, it takes a lot more time.

**Comment by HYTHYThythyt** [comment]
Thank you for your patient reply and your great jobs.

**Comment by HYTHYThythyt** [comment]
And I also want to confirm how many time did you spent in the mask_sem_seg_labels  step when you generated the 82081 masks for the deeplabV2. 
Did you mean using the 82021 images to train deeplabV2 and you spent more than 20 hours? Is there just your one program in your server? Is there any approximate time how long did you spent? Thank you very much!

**Comment by HYTHYThythyt** [comment]
Hi, author. I have some problem in VOC Test dataset. I found that there are a huge gap between val and test. Are there any different config between val and test?

**Comment by HYTHYThythyt** [comment]
Any help is very appreciate!

**Comment by Tiiiktak** [comment]
Sorry for the late reply. 

I'm sorry I can't find the exact time spent on these steps. 

make_sem_seg_labels for all coco images may takes much time, you can change the `n_process_per_gpu` value in `step_coco/make_sem_seg_labels.py#L76` to speed up.

We use the same trained model for evaluation on the val and test sets.

**Comment by Italy2006** [comment]
> Hi, sorry for the confusion.
> 
> The params `MODEL_BACKBONE_DILATED`, `MODEL_BACKBONE_MULTIGRID`, `MODEL_BACKBONE_DEEPBASE` is used by the `generate_net()` at [train.py#L52](https://github.com/YudeWang/semantic-segmentation-codebase/blob/a40f6c6b08710ee1799832c97331cf967e1c5cdb/experiment/deeplabv3%2Bvoc/train.py#L52C139-L52C148). However, these params were not used by the `deeplabv1.py`, so ignore them.
> 
> For the param `MODEL_SCALES`, we apply multi-scale training from [kazuto1011/deeplab-pytorch](https://github.com/kazuto1011/deeplab-pytorch).
> 
> For the `TEST_*` params, we also apply the CRF options from [kazuto1011/deeplab-pytorch](https://github.com/kazuto1011/deeplab-pytorch/blob/master/libs/utils/crf.py), and some multi-processing code to speed up the process.
> 
> You can find our modified code for training the DeepLabV1-WR38 model at [this link](https://drive.google.com/file/d/1OaBxDTRTQLCJjgBS2lkeWOxfdo4MQbqU/view?usp=drive_link)



The (DeepLabV1-WR38 model at [this link](https://drive.google.com/file/d/1OaBxDTRTQLCJjgBS2lkeWOxfdo4MQbqU/view?usp=drive_link))'s permissions have been set, could you authorize me to access it? thank you! Besides, i want to know whether you have tried trainning DeepLabV1-WR38 model on COCO dataset? Thanks!
